### ISSUE TITLE
َAn error on test

### ISSUE THREAD

**Issue by linuxscout** [sohaibafifi/languagetool#20]
Salam,
I have this error when running "./build.sh ar clean test"
`[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.languagetool.rules.ar.ArabicSimpleReplaceRuleTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.044 s <<< FAILURE! - in org.languagetool.rules.ar.ArabicSimpleReplaceRuleTest
[ERROR] testRule(org.languagetool.rules.ar.ArabicSimpleReplaceRuleTest)  Time elapsed: 0.875 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.languagetool.rules.ar.ArabicSimpleReplaceRuleTest.testRule(ArabicSimpleReplaceRuleTest.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

[INFO] Running org.languagetool.rules.ar.ArabicConfusionProbabilityRuleTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s - in org.languagetool.rules.ar.ArabicConfusionProbabilityRuleTest
`

**Comment by sohaibafifi** [comment]
Salem, 
Can you check if you have إنشاء in your replace file ?

**Comment by linuxscout** [comment]
حذفتها، لأنها ليست كلمة واحدة بل كلمتان وهذا الملف هو للاستبدالات البسيطة

**Comment by linuxscout** [comment]
وضعت كلمة إنشاء
لم تعمل، 

ثم جربت كلمة في، ولم تعمل أيضا

**Comment by sohaibafifi** [comment]
What is the error now ? 
Still `arabicsimplereplaceruletest.java:54 `?

**Comment by linuxscout** [comment]
I modify replaces.txt as :

`
?=؟

⁇=؟؟

⁈=؟!

⁉=!؟

إنشاء=إن شاء

يدردشون=يتحدثون

فى=في`


I added  يدردشون, and it's fixed.

I will change examples.

thanks
