### ISSUE TITLE
disambiguator rule tests

### ISSUE THREAD

**Issue by linuxscout** [sohaibafifi/languagetool#6]
I have this error on testing rules.
```sh
Running disambiguator rule tests...
Running disambiguation tests for Arabic...
Exception in thread "main" java.lang.IllegalArgumentException: InputStream cannot be null
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:191)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleLoader.getRules(DisambiguationRuleLoader.java:46)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:76)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.main(DisambiguationRuleTest.java:243)
Running XML bitext pattern tests...

```

**Comment by linuxscout** [comment]
I succeed to resolve this issue by creating the first disambiguation rule.
```xml
   <rule name="Jar" id="Keep_Only_Nouns_after_Jar">
          <!-- work with Prepositions which must precede nouns only -->
          <pattern>
            <token>في</token>
			<marker>
            <token/>
			</marker>
          </pattern>
		  <disambig><match no="2" postag="N.*" postag_regexp="yes" /></disambig>
          <example type="ambiguous" inputform="عامل[عامل/NA-;M1--;---,عامل/NA-;M1A-;---,عامل/NA-;M1I-;---,عامل/NA-;M1U-;---,عَامَلَ/VW1;M1A-iaH;---,عَامَلَ/VW1;M1A-ipY;---]" outputform="عامل[عامل/NA-;M1--;---,عامل/NA-;M1A-;---,عامل/NA-;M1I-;---,عامل/NA-;M1U-;---]">
رأيت التفاني في <marker>عامل</marker> النظافة.</example>
        </rule>
```
